(SIMP-3430) Create Centralized spec_helper.rb
simp/rubygem-simp-spec-helpers pull request #2
Opened 2020-01-24 21:20 UTC by jeannegreulich

- created baseline for spec_helper.rb
      to do basc RSPEC configuration for SIMP module unit tests.
    - added some basic methods that were also in spec_helpers
    - added compliance markup methods for use in compliance
      markup unit tests.
    
    SIMP-3430 #comment added simp-spec-helpers

2020-02-05 16:54 UTC, op-ct requested changes
Thanks for this patch--It's about time we returned to the the idea of centralizing our spec helper logic into a single gem.  

Some concerns:

* A monolithic `global_spec_helper` method may prescribe too much common functionality without providing individual modules' hooks to alter it (for instance, the current implementation makes `default_hiera_config` the only possible hiera config).
* Quite a few line-item comments address things that are probably copypasta residue, like really old spec helper practices (like, last relevant in 2015 old) and updates to Hiera 5. 
* Now that we've centralized all this logic, the gem should probably have spec tests for it.
* We'll need to take care that it doesn't introduce circular gem dependencies, though (IIRC, our previous attempt would have).

2020-02-05 16:54 UTC, op-ct commented on .travis.yml
> +  - SIMP_SKIP_NON_SIMPOS_TESTS=1
Is `SIMP_SKIP_NON_SIMPOS_TESTS` used by anything?  It's not referenced in any other code in the repository.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +      c.mock_with  :mocha
Mock with `:rspec`, not `:mocha`.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +      FileUtils.mkdir_p(File.join(fixture_path,'hieradata'))
This looks like legacy logic that should go away
* nothing bad happens when a Hiera 5 datadir path doesn't exist.
* `hieradata/` is a Hiera ≤4 naming convention.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +      FileUtils.mkdir_p(File.join(fixture_path,'modules',module_name))
This `mkdir_p` seems unnecessary.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +    default_hiera_config =<<~EOM
We should probably expose a parameter that can override  `default_hiera_config` (or just use `fixtures/hiera.yaml` if it already exists).  Other wise, this is the _only possible_ Hiera config.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +            data[key][:datadir] = File.join(fixture_path, 'hieradata')
Hiera 5 can handle relative paths, so the "stub" logic should go away:

1. `File.join` is no longer necessary
2. The intended (relative path) for datadir can defined in the `default_hiera_config` above

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +        datadir: "stub"
Hiera 5 can use relative paths, so the `datadir: "stub"` + substitution logic isn't necessary

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +        File.open(c.hiera_config, 'w') do |f|
We should consider doing nothing if  `fixtures/hiera.yaml` already exists.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +      c.hiera_config = File.join(fixture_path,'hieradata','hiera.yaml')
`hieradata/` is a Hiera ≤4 naming convention; `data/` would be more consistent with Hiera 5.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +  def set_environment(environment = :production)
This method appears to be unnecessary vs rspec-puppet's [`let(:environment)`](https://rspec-puppet.com/documentation/classes/#specifying-the-environment-name) block.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +  def set_hieradata(hieradata)
`set_hieradata` doesn't set Hiera data—it defines a custom hiera hierarchy key.
The Hiera data already needs to exist in the file `%{datadir}/%{custom_hiera}.yaml`.

2020-02-05 16:54 UTC, op-ct commented on simp-spec-helpers.gemspec
> +  s.add_development_dependency  'puppetlabs_spec_helper', '~> 0'
This should probably be something like `~> 2.0` or `~> 2.4`; puppetlabs_spec_helper `~> 0` is ancient (2015).

```suggestion
  s.add_development_dependency  'puppetlabs_spec_helper', '~> 2.0'
```

2020-02-05 16:54 UTC, op-ct commented on simp-spec-helpers.gemspec
> +  s.add_development_dependency  'puppetlabs_spec_helper', '~> 0'
It would be better to specify these gems using [`add_runtime_dependency`](https://guides.rubygems.org/specification-reference/#add_runtime_dependency)—the code under this gem's `lib/` directory needs them to work.

2020-02-05 16:54 UTC, op-ct commented on README.md
> +require 'pathname'
pathname isn't required by anything here; it is only used once in `lib/simp/spec_helpers/helpers.rb `

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +    if ENV['PUPPET_DEBUG']
Test for something specific,  like `yes` or `true`, so it can still be overridden and disabled with `no`

2020-02-05 16:54 UTC, op-ct commented on Rakefile
> +SIMP_RPM_BUILD     when set, alters the gem produced by pkg:gem to be RPM-safe.
Shouldn't this `:help` task be defined by whatever provides `pkg:gem`?

2020-02-05 16:54 UTC, op-ct commented on README.md
> +global_spec_helper(fixture_path, module_name)
I'd pass in `__FILE__` instead of `fixture_path` and `module_name`.   Then `global_spec_helper()` can find all these files, (including `spec_helper_local.rb`).

2020-02-05 16:54 UTC, op-ct commented on README.md
> +``` ruby
Most of this code block should probably go inside the `global_spec_helper()` method and/or the Simp::SpecHelpers Ruby module.  Otherwise, this block would still need to be kept in sync across every module's `spec_helper.rb`.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +  def global_spec_helper(fixture_path, module_name)
Instead of passing in `fixture_path` and `module_name`, pass in `__FILE__`.   That way `global_spec_helper()` can find both files and load `spec_helper_local.rb`.

2020-02-05 16:54 UTC, op-ct commented on Rakefile
> +desc "Run spec tests"
There aren't any spec tests for this task to run.

2020-02-05 16:54 UTC, op-ct commented on .travis.yml
> +      secure: "need key"
Thanks for the reminder--I'll update this with a Travis variable in a later PR.

2020-02-05 16:54 UTC, op-ct commented on lib/simp/spec_helpers/version.rb
> +  VERSION = '0.0.2'
This patch adds new API functionality.

```suggestion
  VERSION = '0.1.0'
```

2020-02-05 16:54 UTC, op-ct commented on Gemfile
> +  gem 'rspec'
`rspec` is already included by the .gemspec file.  Unless the Gemfile's `gem` statement refines a gemspec's gem (like  how `PUPPET_VERSION` refines the `puppet` gem) there shouldn't be any redundant gems.

2020-02-05 16:54 UTC, op-ct commented on Rakefile
> +task :chmod do
This task should be defined alongside `pkg:gem`

2020-02-07 19:14 UTC, jeannegreulich commented on lib/simp/spec_helpers/helpers.rb
> +      c.mock_with  :mocha
most of them mok with mocha.  You can overwrite it in the spec_helpers_local (example in README.)   When we have moved most of our stuff over, we can change the default to rspec.

2020-02-25 00:15 UTC, op-ct commented on lib/simp/spec_helpers/helpers.rb
> +      c.mock_with  :mocha
Most of our modules are configured for mocha as a matter of copy/pasta, but they don't actually mock anything—they run just as fine when configured for `:rspec` (I just tested this on a simp-core + `rake deps:checkout`, setting up a big bash loop over the `simp-` modules to make the changes to spec/spec_helper.rb and running spec tests for each one).

My concern is that there are problems with mocking in mocha<sup>[1]</sup> compared to rspec-mocks, and most of our modules aren't very invested yet.  So I'd flip it around—we should encourage `:rspec` by default, and allow the modules who really can't and overwrite the spec_helpers_local for the modules that just can't switch just yet.

[1]: https://github.com/voxpupuli/plumbing/issues/78

2020-02-27 16:00 UTC, jeannegreulich commented on lib/simp/spec_helpers/helpers.rb
> +    default_hiera_config =<<~EOM
Put in a ticket for improvements. I was trying to centralize it so we could in the futre update from one place not optimize it to the nth degree.  I took hat we had and centralized it so when we the latest ticket we could put in the changes to call this and then the next ticket would only require updates to this.

2020-02-27 16:02 UTC, jeannegreulich commented
I let Chris write his own update.

2020-02-27 16:02 UTC, closed without merging